export type Filter = {
  key: string;
  label: string;
  type: "dropdown" | "checkbox" | "range" | "rating";
  options?: string[] | number[];
  min?: number;
  max?: number;
  step?: number;
  unit?: string;
};

export const filtersConfig: Record<string, Filter[]> = {
  all: [],
  restaurant: [
    {
      key: "cuisine",
      label: "Тип кухни",
      type: "dropdown",
      options: [
        "Итальянская",
        "Французская",
        "Японская",
        "Китайская",
        "Грузинская",
        "Европейская",
        "Русская",
        "Американская",
      ],
    },
    {
      key: "priceLevel",
      label: "Средний чек",
      type: "range",
      min: 300,
      max: 5000,
      step: 100,
      unit: "₽",
    },
    {
      key: "rating",
      label: "Рейтинг",
      type: "rating",
      min: 1,
      max: 5,
      step: 0.5,
    },
    {
      key: "hasDelivery",
      label: "Есть доставка",
      type: "checkbox",
    },
    {
      key: "isVegetarianFriendly",
      label: "Вегетарианское меню",
      type: "checkbox",
    },
  ],
  cofee: [
    {
      key: "coffeeType",
      label: "Тип кофе",
      type: "dropdown",
      options: ["Арабика", "Робуста", "Смесь"],
    },
    {
      key: "beansOrigin",
      label: "Страна происхождения",
      type: "dropdown",
      options: [
        "Бразилия",
        "Колумбия",
        "Эфиопия",
        "Вьетнам",
        "Индонезия",
        "Другое",
      ],
    },
    {
      key: "price",
      label: "Цена за кг",
      type: "range",
      min: 500,
      max: 5000,
      step: 50,
      unit: "₽",
    },
    {
      key: "isOrganic",
      label: "Органический продукт",
      type: "checkbox",
    },
  ],
  hotel: [
    {
      key: "stars",
      label: "Количество звёзд",
      type: "dropdown",
      options: ["1★", "2★", "3★", "4★", "5★"],
    },
    {
      key: "pricePerNight",
      label: "Цена за ночь",
      type: "range",
      min: 1000,
      max: 30000,
      step: 500,
      unit: "₽",
    },
    {
      key: "hasBreakfast",
      label: "Завтрак включён",
      type: "checkbox",
    },
    {
      key: "hasParking",
      label: "Парковка",
      type: "checkbox",
    },
    {
      key: "rating",
      label: "Рейтинг",
      type: "rating",
      min: 1,
      max: 5,
      step: 0.5,
    },
  ],
  bar: [
    {
      key: "barType",
      label: "Тип заведения",
      type: "dropdown",
      options: ["Паб", "Коктейль-бар", "Винный бар", "Крафт-бар", "Лаунж"],
    },
    {
      key: "priceLevel",
      label: "Средний чек",
      type: "range",
      min: 300,
      max: 5000,
      step: 100,
      unit: "₽",
    },
    {
      key: "hasLiveMusic",
      label: "Живая музыка",
      type: "checkbox",
    },
    {
      key: "openLate",
      label: "Работает допоздна",
      type: "checkbox",
    },
    {
      key: "rating",
      label: "Рейтинг",
      type: "rating",
      min: 1,
      max: 5,
      step: 0.5,
    },
  ],
  office: [
    {
      key: "officeType",
      label: "Тип офиса",
      type: "dropdown",
      options: [
        "Коворкинг",
        "Бизнес-центр",
        "Офисное здание",
        "Гибкий офис",
        "Другое",
      ],
    },
    {
      key: "workplaces",
      label: "Кол-во рабочих мест",
      type: "range",
      min: 1,
      max: 500,
      step: 1,
    },
    {
      key: "hasMeetingRoom",
      label: "Есть переговорная",
      type: "checkbox",
    },
    {
      key: "hasParking",
      label: "Парковка",
      type: "checkbox",
    },
  ],
  store: [
    {
      key: "storeType",
      label: "Тип магазина",
      type: "dropdown",
      options: [
        "Продукты",
        "Одежда",
        "Электроника",
        "Дом и сад",
        "Товары для детей",
        "Аптека",
        "Другое",
      ],
    },
    {
      key: "area",
      label: "Площадь (м²)",
      type: "range",
      min: 10,
      max: 5000,
      step: 10,
      unit: "м²",
    },
    {
      key: "hasDelivery",
      label: "Есть доставка",
      type: "checkbox",
    },
    {
      key: "rating",
      label: "Рейтинг",
      type: "rating",
      min: 1,
      max: 5,
      step: 0.5,
    },
  ],
  fitness: [
    {
      key: "fitnessType",
      label: "Тип клуба",
      type: "dropdown",
      options: [
        "Фитнес",
        "Тренажёрный зал",
        "Йога-студия",
        "Плавательный бассейн",
        "Танцевальная студия",
        "Другое",
      ],
    },
    {
      key: "pricePerMonth",
      label: "Цена абонемента/мес",
      type: "range",
      min: 1000,
      max: 20000,
      step: 500,
      unit: "₽",
    },
    {
      key: "hasPool",
      label: "Бассейн",
      type: "checkbox",
    },
    {
      key: "hasGroupPrograms",
      label: "Групповые программы",
      type: "checkbox",
    },
    {
      key: "rating",
      label: "Рейтинг",
      type: "rating",
      min: 1,
      max: 5,
      step: 0.5,
    },
  ],
  event: [
    {
      key: "eventType",
      label: "Тип мероприятия",
      type: "dropdown",
      options: [
        "Свадьба",
        "Детский праздник",
        "Корпоратив",
        "Концерт",
        "Выставка",
        "Другое",
      ],
    },
    {
      key: "guests",
      label: "Кол-во гостей",
      type: "range",
      min: 10,
      max: 1000,
      step: 10,
    },
    {
      key: "hasCatering",
      label: "Кейтеринг",
      type: "checkbox",
    },
    {
      key: "hasDecoration",
      label: "Декорирование",
      type: "checkbox",
    },
    {
      key: "rating",
      label: "Рейтинг",
      type: "rating",
      min: 1,
      max: 5,
      step: 0.5,
    },
  ],
  transport: [
    {
      key: "transportType",
      label: "Тип транспорта",
      type: "dropdown",
      options: [
        "Автобус",
        "Минивэн",
        "Легковое авто",
        "Грузовик",
        "Лимузин",
        "Другое",
      ],
    },
    {
      key: "capacity",
      label: "Вместимость",
      type: "range",
      min: 2,
      max: 100,
      step: 1,
    },
    {
      key: "hasDriver",
      label: "С водителем",
      type: "checkbox",
    },
    {
      key: "hasAC",
      label: "Кондиционер",
      type: "checkbox",
    },
  ],
  medical: [
    {
      key: "medicalType",
      label: "Тип учреждения",
      type: "dropdown",
      options: [
        "Клиника",
        "Стоматология",
        "Скорая помощь",
        "Диагностический центр",
        "Аптека",
        "Другое",
      ],
    },
    {
      key: "has24h",
      label: "Круглосуточно",
      type: "checkbox",
    },
    {
      key: "hasInsurance",
      label: "Работает с ДМС",
      type: "checkbox",
    },
    {
      key: "rating",
      label: "Рейтинг",
      type: "rating",
      min: 1,
      max: 5,
      step: 0.5,
    },
  ],
  education: [
    {
      key: "educationType",
      label: "Тип учреждения",
      type: "dropdown",
      options: [
        "Школа",
        "ВУЗ",
        "Колледж",
        "Детский сад",
        "Онлайн-курсы",
        "Другое",
      ],
    },
    {
      key: "students",
      label: "Кол-во учеников",
      type: "range",
      min: 10,
      max: 2000,
      step: 10,
    },
    {
      key: "hasBoarding",
      label: "Интернат",
      type: "checkbox",
    },
    {
      key: "hasAfterSchool",
      label: "Группы продленного дня",
      type: "checkbox",
    },
    {
      key: "rating",
      label: "Рейтинг",
      type: "rating",
      min: 1,
      max: 5,
      step: 0.5,
    },
  ],
  construction: [
    {
      key: "constructionType",
      label: "Тип работ",
      type: "dropdown",
      options: [
        "Ремонт",
        "Строительство",
        "Дизайн/архитектура",
        "Инженерные сети",
        "Отделка",
        "Другое",
      ],
    },
    {
      key: "area",
      label: "Площадь (м²)",
      type: "range",
      min: 10,
      max: 10000,
      step: 10,
      unit: "м²",
    },
    {
      key: "hasMaterials",
      label: "С материалами",
      type: "checkbox",
    },
    {
      key: "hasWarranty",
      label: "Гарантия",
      type: "checkbox",
    },
    {
      key: "rating",
      label: "Рейтинг",
      type: "rating",
      min: 1,
      max: 5,
      step: 0.5,
    },
  ],
  default: [],
};
